### PR TITLE
Adds a button for paper submissions to the homepage

### PR DESCRIPTION
**Pull request by briangow**
This adds a button for paper submissions to the homepage. The submit your paper button on the call for papers page remains as well.

### CODE REVIEW

**Comment by tompollard** [comment]
Looks good to me! It would be good if the buttons followed the same style ("PREREGISTER TODAY!") and ("Submit your paper"), but it seems fine otherwise. Do you want to change this now or save for a later PR?

**Comment by briangow** [comment]
@tompollard , thanks for taking a look! What specifically are you thinking should match in style? Cap lock, color, button class? Here are the button classes:

PREREGISTER: `class="btn-primary btn-lg"`
Submit: `class="btn btn-primary btn-lg active"`

I think I like it that the colors are different but am open to changing any of these parameters.

**Comment by tompollard** [comment]
Main thing is matching the casing I think. Personally I'd change "PREREGISTER TODAY!" to "Pre-register today". Looking at the style, I'd also match the button size (btn-lg for both or for neither). I like the look of btn-lg. I don't have any particular feeling about same vs different colour.



btn-lg

**Comment by tompollard** [comment]
thanks, looks good to me!

**Comment by briangow** [comment]
@tompollard I updated the case of the pre-register button.

**Pull request merged**
